"""Add BlockedUser model

Revision ID: 58467bb10a26
Revises: 7ef2a3d25d06
Create Date: 2026-01-17 17:21:29.599598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58467bb10a26'
down_revision = '7ef2a3d25d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='unique_block')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blocked_user')
    # ### end Alembic commands ###
